version: '3.1'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: document-management
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    environment:
      PORT: 3001
      JWT_SECRET: thaihoangtest
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASS: 12345678
      DATABASE_NAME: document-management
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  db_data:
