version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: document-management
      MYSQL_PASSWORD: admin_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
