version: '3.1'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: document-management
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASS: 12345678
      DATABASE_NAME: document-management
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npm run build && ./wait-for-it.sh db:3306 -- npm run start:prod"

volumes:
  db_data:
